# Generated by Django 4.2.27 on 2025-12-08 10:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tmdb_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("year", models.PositiveIntegerField()),
                ("poster_path", models.CharField(blank=True, max_length=500)),
                ("runtime", models.PositiveIntegerField(blank=True, null=True)),
                ("critic_score", models.FloatField(blank=True, null=True)),
                ("popularity", models.FloatField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-year", "title"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("tmdb_id", models.IntegerField(unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("tmdb_id", models.IntegerField(unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("tmdb_id", models.IntegerField(unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FilmPerson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("director", "Director"), ("cast", "Cast")],
                        max_length=20,
                    ),
                ),
                ("billing_order", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="film_people",
                        to="films.film",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="film_people",
                        to="films.person",
                    ),
                ),
            ],
            options={
                "ordering": ["film", "role", "billing_order"],
                "unique_together": {("film", "person", "role")},
            },
        ),
        migrations.CreateModel(
            name="FilmKeyword",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="film_keywords",
                        to="films.film",
                    ),
                ),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="film_keywords",
                        to="films.keyword",
                    ),
                ),
            ],
            options={
                "unique_together": {("film", "keyword")},
            },
        ),
        migrations.CreateModel(
            name="FilmGenre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="film_genres",
                        to="films.film",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="film_genres",
                        to="films.genre",
                    ),
                ),
            ],
            options={
                "unique_together": {("film", "genre")},
            },
        ),
        migrations.AddField(
            model_name="film",
            name="genres",
            field=models.ManyToManyField(
                blank=True,
                related_name="films",
                through="films.FilmGenre",
                to="films.genre",
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="keywords",
            field=models.ManyToManyField(
                blank=True,
                related_name="films",
                through="films.FilmKeyword",
                to="films.keyword",
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="people",
            field=models.ManyToManyField(
                blank=True,
                related_name="films",
                through="films.FilmPerson",
                to="films.person",
            ),
        ),
    ]
