# Generated by Django 4.2.27 on 2025-12-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
